client_app/base/urls.py
from django.urls import path
from . import views

app_name = 'base'

# URLConf
urlpatterns = [
    path('', views.landing, name='landing'),
    path('home', views.home, name='home'),
    path('questionaire', views.questionaire, name='questionaire'),
]

client_app/client_app/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('base.urls')),
    path('admin/', admin.site.urls),
]

client_app/base/forms.py
from django import forms
from django.urls import reverse_lazy
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

class DiabetesForm(forms.Form):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.form_action = reverse_lazy('base:home')
        self.helper.form_method = 'GET'
        self.helper.add_input(Submit('submit', 'Submit'))

    high_bp = forms.IntegerField(label="Do you have high Blood Pressure?", required=True, min_value=0, max_value=1)
    high_chol = forms.IntegerField(label="Do you have high Cholesterol?", required=True, min_value=0, max_value=1)
    chol_check = forms.IntegerField(label="Did you check your Cholesterol in last 5 years?", required=True, min_value=0, max_value=1)
    weight = forms.FloatField(label="How much do you weigh in kilograms?", required=True,)
    height = forms.FloatField(label="How tall are you in centimeters?", required=True,)
    smoker = forms.IntegerField(label="Have you smoked at least 100 cigarettes in your entire life?", required=True, min_value=0, max_value=1)
    stroke = forms.IntegerField(label="Have you ever had a stroke before?", required=True, min_value=0, max_value=1)
    heart = forms.IntegerField(label="Have you ever had coronary heart disease (CHD) or myocardial infarction (MI)?", required=True, min_value=0, max_value=1)
    pa = forms.IntegerField(label="Have you done any physical activity in past 30 days excluding your job?", required=True, min_value=0, max_value=1)
    fruits = forms.IntegerField(label="Do you consume fruits once or more times per day?", required=True, min_value=0, max_value=1)
    

client_app/base/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

from .forms import DiabetesForm

# Create your views here.
def landing(request):
    return render(request, 'landing.html')

def home(request):
    return render(request, 'home.html')

def questionaire(request):
    if request.method == 'POST':
        # create a form instance and populate it with data from the request:
        form = DiabetesForm(request.POST)
        # check whether it's valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required
            # ...
            # redirect to a new URL:
            return HttpResponseRedirect('/')

    # if a GET (or any other method) we'll create a blank form
    else:
        form = DiabetesForm()

    return render(request, 'questionaire.html', {'form': form})

client_app/base/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    <title> {{ pagetitle }} Client App</title>
</head>

<body>
    <header>
        {% include 'partials/nav.html' %}
    </header>

    <main>
        {% block extend_body %} 
        {% comment %} Extended body goes here {% endcomment %} 
        {% endblock extend_body %}
    </main>

    <footer>

    </footer>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>

</html>

client_app/base/templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block extend_body %}

<div class="container home-page">
    <div class="mt-5 text-center">
        <h2>Secure Cloud &#8212; Client Portal</h2>
        <h5>Home Page &nbsp; <code>&lt;In Development&gt;</code></h5>
    </div>
    <hr>
    <div class="mt-5">
    <p>
        Here we have a demo example of how your data can be sent to the cloud without the cloud knowing what your data is. The cloud is hosting a diabetes predicting model trained with public data. You can fill-out a questionaire about your health information and your given information will be encrypted and sent to the cloud.
        <br>
        The result generated from the cloud can then be decrypted by you using your private key and you can see the test results based on your given information.
    </p>
    <a class="btn btn-primary" href="{% url 'base:questionaire' %}">Fill-out the questionaire</a>
    </div>
</div>
{% endblock extend_body %}

client_app/base/templates/landing.html
{% extends 'base.html' %} 
{% load static %}

{% block extend_body %}

<div class="container landing-page">
    <div class="mt-5 text-center">
        <h2>Secure Cloud &#8212; Client Portal</h2>
        <h5>Log in or create a new account</h5>
    </div>
    <div class="mt-5 text-center">
        <a href="" class="btn btn-lg btn-primary mx-2">Log In <i class="bi bi-box-arrow-in-right"></i></a>
        <a href="" class="btn btn-lg btn-primary mx-2">Sign Up <i class="bi bi-person-plus"></i></a>
    </div>
</div>
{% endblock extend_body %}

client_app/base/templates/partials/nav.html
{% load static %}

<nav class="navbar navbar-expand-lg">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'base:landing' %}"">Secure Cloud</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'base:home' %}"">Home</a>
                </li>
                <li class="nav-item">   
                    <a class="nav-link" href="#">Keys</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Data</a>
                </li>
            </ul>
            <span class="navbar-text">
                Welcome, user!
            </span>
        </div>
    </div>
</nav>

client_app/base/templates/questionaire.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block extend_body %}

<div class="container home-page">
    <div class="mt-5 text-center">
        <h2>Secure Cloud &#8212; Client Portal</h2>
        <h5>Diabetes Questionaire &nbsp; <code>&lt;In Development&gt;</code></h5>
    </div>
    <hr>
    <div class="my-5">
    <p class="my-3">(<strong>For Yes/No Questions:</strong> No = 0, Yes = 1)</p>
    <form method="POST" class="">
        {% csrf_token %}
        {% comment %} {{ form }} {% endcomment %}

        {% crispy form %}
    </form>
    </div>
</div>
{% endblock extend_body %}